exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings, flake8-debugger, flake8-bugbear]

ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
  autoupdate_schedule: "monthly"