version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - python -c "import os; print(os.getcwd()); import sys; print(sys.path)"
      - python setup.py build_ext --inplace
      - cd doc
      - python -c "import sys; print(sys.path); import trollimage.tests; print(trollimage.tests.__file__)"
      - python -c "import trollimage.tests.test_colormap"
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
python:
  install:
    - requirements: rtd_requirements.txt
    - method: pip
      path: .
