language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
  - "pip install ."
  - "pip install coveralls"
# command to run tests
script: 
  coverage run --source=trollimage setup.py test
after_success:
  coveralls
