language: python
env:
    global:
        # Set defaults to avoid repeating in most cases
        - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - NUMPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='pillow gdal xarray dask toolz coverage coveralls codecov rasterio pytest pytest-cov'
        - SETUP_XVFB=False
        - EVENT_TYPE='push pull_request'
        - SETUP_CMD='test'
        - CONDA_CHANNELS='conda-forge'
        - CONDA_CHANNEL_PRIORITY=True
        - UNSTABLE_DEPS=False

matrix:
  include:
  - env: PYTHON_VERSION=3.7
    os: linux
  - env: PYTHON_VERSION=3.8
    os: linux
  - env:
    - PYTHON_VERSION=3.8
    - UNSTABLE_DEPS=True
    os: linux
  allow_failures:
    - env:
        - PYTHON_VERSION=3.8
        - UNSTABLE_DEPS=True
      os: linux

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - if [ "$UNSTABLE_DEPS" == "True" ]; then
    python -m pip install
    -f https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com
    --no-deps --pre --upgrade
    numpy
    pandas;
    python -m pip install
    --no-deps --upgrade
    git+https://github.com/dask/dask
    git+https://github.com/mapbox/rasterio
    git+https://github.com/pydata/xarray;
    fi
  - pip install -e . --no-deps
script:
  - pytest --cov=trollimage trollimage/tests
after_success:
  - if [[ $PYTHON_VERSION == 3.8 ]]; then coveralls; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: "Cpo7kPgjbyWKNRjnzWDggxo5dqG8KdtcrBxYWwBpkkhgly/ngN9EkjIdscrwmp8sCqfjTd0RGyR811k6dzU7kKJVbc6V309+4mG8O0w4IvfHCn+NaHymAMrHleRIqyxbo5kvrBZoX+eB7YWOUppF6ofeohbrNWWgMQv+/d+Mufs="
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      repo: pytroll/trollimage
      tags: true
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
